import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { FirebaseProvider } from "@/models/Firebase_config";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FirebaseProvider>
          <div className="md:p-4 px-10 py-4 flex flex-col">
            <Header />
            {children}
          </div>
        </FirebaseProvider>
      </body>
    </html>
  );
}
